### ISSUE TITLE
Unable to use this library

### ISSUE THREAD

**Issue by lisitso** [jrichardsz/lib-java-google-translate-text-to-speech#1]
Hi, I downloaded your code and followed the instructions to setup the project.
Everything compiles but at runtime I get an exception from the api.

Please could you tell how to get it working?
Thanks in advance.
L.

Exception in thread "main" java.io.IOException: Server returned HTTP response code: 503 for URL: http://ipv4.google.com/sorry/IndexRedirect?continue=http://translate.google.com/translate_tts%3Fq%3DHello%2520Richard%26tl%3Den&q=CGMSBALsIpoYpMvvrwUiGQDxp4NLUaaWLutnZPggHWm5g4ShyJMZras
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626)
    at com.gtranslate.Audio.getAudio(Audio.java:31)
    at org.openqa.selenium.example.Text2Speech.main(Text2Speech.java:62)

**Comment by jrichardsz** [comment]
Hi lisistso.
Please check this issue : 
https://github.com/jrichardsz/appdesktop-super-translator/issues/3

This is the explanation :  

"Users forced to enter Captcha by Google when used extensively the translator. code: 503"

What are you using this tool?

Translate words?
Text To Speech?

I working in a solution for this : 
1.- If  HTTP response code is 503, use a new engine.
2.- New Engine use a HtmlUnit. This api can manipulate dom html of any web. This api is used for test automation for software quality assurance teams.
3.- This engine go to : https://translate.google.com/?hl=es&tab=wT , obtains response as dom, set "hello" in text area ( left side ) and press button "translator", obtain new response dom  and get translated text for text area in right side.

I tried and it works!  I am improving the library. In a couple of days I will make the push!

Regards.

**Comment by lisitso** [comment]
Hi @jrichardsz 

I'm using the text2speech tool.
When I do this:
Audio.getInstance().play(Audio.getInstance().getAudio("Buongiorno mondo", Language.ITALIAN));

I get this error:
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 503 for URL: http://ipv4.google.com/sorry/IndexRedirect?continue=http://translate.google.com/translate_tts%3Fq%3DBuongiorno%2520mondo%26tl%3Dit&q=CGMSBALsIpoY6Lb0rwUiGQDxp4NLQ4DDiw-p0cuNSARIss2Lch8xvQo

the line of code that fails is Audio::getAudio()

> > InputStream audioSrc = urlConn.getInputStream();

How's possible to fix it?

Regards

**Comment by jrichardsz** [comment]
Hi Lisitso.
I complete a new tts api. This use a bing api instead google api.

https://github.com/jrichardsz/bing-tts-api

Regards.

**Comment by lisitso** [comment]
Hi @jrichardsz 
thank you for your support.
Unfortunately this new api is not working. I run the example code and this is the output:

Exception in thread "main" java.io.IOException: Server returned HTTP response code: 400 for URL: http://api.microsofttranslator.com/v2/http.svc/speak?appId=TyYTiDGMltI66a4CYYlJ9e23cfF_hgv8zTXuinMoPvoY*&language=it-IT&format=audio/mp3&options=MinSize|male&text=Buongiorno%20mondo
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626)
    at com.bing.translate.tts.sound.Audio.getAudio(Audio.java:35)
    at com.bing.translate.tts.MainBingTranslate.main(MainBingTranslate.java:24)

Any idea?
Regards

**Comment by jrichardsz** [comment]
Please check this issue : 
https://github.com/jrichardsz/bing-tts-api/issues/1
